### PR TITLE
Migrate to Lua

### PR DESCRIPTION
**Pull request by luan**
For user config something like this is necessary: https://github.com/luan/dotfiles/commit/c6387cb9cc43b54ac005a74a12c89eec7704740f

Everything else should just work. But I'm keeping this on a branch for a little bit.

If you would like to try this out, just `git checkout lua` at `~/.config/nvim` and start vim again. You might get some errors, if you do, post them here. You can probably unblock yourself by running `:PackerSync` manually.

### CODE REVIEW

**Comment by luan** [comment]
@utako @kirederik @jaresty @jfmyers9 @kauana my favorite beta testers

**Comment by XenoPhex** [comment]
Not sure what's expected and what isn't. Just switched branches and got the following issue when open nvim (stable 0.5.0):
```
Error detected while processing /Users/anand/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/anand/.config/nvim/lua/update.lua:1: module 'packer.jobs' not found:
        no field package.preload['packer.jobs']
        no file './packer/jobs.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer/jobs.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer/jobs/init.lua'
        no file './packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/packer/jobs.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by luan** [comment]
@XenoPhex It should've installed packer as the first thing. It sounds like that may not have happened successfully. Anything else on `:messages` (before this error)

**Comment by XenoPhex** [comment]
Unfortunately this is all I get:
```
Error detected while processing /Users/anand/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/anand/.config/nvim/lua/update.lua:1: module 'packer.jobs' not found:
        no field package.preload['packer.jobs']
        no file './packer/jobs.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs/init.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer/jobs.lua'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/packer/jobs/init.lua'
        no file './packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/packer/jobs.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```

**Comment by XenoPhex** [comment]
I don't actually see anything in `init.lua` or `lua/globals.lua` that installs packer if it's not there; when `lua/update.lua` runs, the first line seems to assume packer is installed.

For now I'm going to [manually install packer](https://github.com/wbthomason/packer.nvim#quickstart) for now to proceed. Let me know if you think you've fixed the bootstrap process and I can give things another try.

**Comment by XenoPhex** [comment]
Next error I'm getting (after I install packer):
```
Error detected while processing /Users/anand/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/anand/.config/nvim/lua/colorscheme.lua:1: Vim(colorscheme):E18
5: Cannot find color scheme 'neon'
```

**Comment by XenoPhex** [comment]
Not sure why, but apparently `gnu-sed` is a requirement now according to `:messages`:
```
You need to install gnu sed 'brew instal gnu-sed'
```

**Comment by XenoPhex** [comment]
I'm also getting the following error when I try and `gd` on a random function in go:
```
LSP: no client attached
```

**Comment by jfmyers9** [comment]
`:LspInstall go`? Also I have had not nearly as many problems as you have @XenoPhex

**Comment by XenoPhex** [comment]
@jfmyers9 so what I'm hearing is that I'm winning the bug race 😆 

I'm also on a pretty vanilla Big Sur install, I've been keeping this machine super light (don't even have chrome installed). So imagine that might be a source of more issues.

**Comment by jfmyers9** [comment]
Maybe I should update to Big Sur tonight...

**Comment by XenoPhex** [comment]
If you do, I'd recommend [Safari Technology Preview](https://developer.apple.com/safari/technology-preview/) I was surprised as to how much smoother it is than Chrome / Firefox.

**Comment by XenoPhex** [comment]
Do I need to do anything additional (outside of the `:LspInstall go`) to get things like `:A` to work with go?

I also noticed there's `No code actions available` when I use the `space + l + a` shortcut via Lsp.

**Comment by luan** [comment]
This is what installs packer: https://github.com/luan/nvim/blob/lua/lua/packer-init.lua but it sounds like whatever I tried to automate there just didn't work for you. I'll try to repro some of this in a container or something that doesn't have everything installed to see what I can figure out.

`:A` comes from https://github.com/tpope/vim-projectionist -- I could probably just add that back.

Code actions will only be available in certain circumstances, I haven't actually used them much. But do you have reason to expect code actions in that context?

**Comment by jaresty** [comment]
I also ran into this issue:
```
Error detected while processing /home/admin/.config/luan-nvim/init.lua:
E5113: Error while calling lua chunk: /home/admin/.config/nvim/lua/update.lua:1: module 'packer.jobs' not found:
        no field package.preload['packer.jobs']
        no file './packer/jobs.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs.lua'
        no file '/usr/local/share/lua/5.1/packer/jobs/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/packer/jobs.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/packer/jobs/init.lua'
        no file './packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/packer/jobs.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/packer/jobs.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
        no file './packer.so'
        no file '/usr/local/lib/lua/5.1/packer.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/packer.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
```

**Comment by luan** [comment]
I had a silly mistake in `init.lua` that I pushed a fix for now. packer should auto-install properly now

**Comment by XenoPhex** [comment]
Packer now seems to install properly, but I now get the following error with treesitter:
```
[packer.nvim] [ERROR 12:08:30] async.lua:20: Error in coroutine: ...ack/packer/start/packer.nvim/lua/packer/plugin_utils.lua:204: Vim(lua):E5108: Error executing lua ...eesitter-textobjects/lua/nvim-treesitter-texto
bjects.lua:1: module 'nvim-treesitter.query' not found:
[packer.nvim] ^Ino field package.preload['nvim-treesitter.query']
[packer.nvim] ^Ino file './nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/usr/local/share/lua/5.1/nvim-treesitter/query/init.lua'
[packer.nvim] ^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/nvim-treesitter/query/init.lua'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/query/init.lua'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/query.lua'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/query/init.lua'
[packer.nvim] ^Ino file './nvim-treesitter/query.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter/query.so'
[packer.nvim] ^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/nvim-treesitter/query.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter/query.so'
[packer.nvim] ^Ino file './nvim-treesitter.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
[packer.nvim] ^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/nvim-treesitter.so'
[packer.nvim] ^Ino file '/usr/local/lib/lua/5.1/loadall.so'
[packer.nvim] ^Ino file '/Users/anand/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter.so'
```

This seems to be solved by restarting vim and rerunning packer sync (and the rest of the install proceeds).

> :A comes from https://github.com/tpope/vim-projectionist -- I could probably just add that back.
>
> Code actions will only be available in certain circumstances, I haven't actually used them much. But do you have reason to expect code actions in that context?

I think I misunderstood what code actions were; I was just looking to have nvim continue to with code folding, jumping to the alternate file, and some other related actions which (at this moment I don't remember what was missing, but at least these two that I mentioned) were not happening.

I'll add projectionist to my user plugin list and I'll see if I can setup treesitter to support folding.

**Comment by XenoPhex** [comment]
From the look of it, on the occasion that the textobjects repo does clone properly (from a clean `.local/share/nvim` dir), I then I get the following error (extra log lines copied from the `:messages` command):

```
remote/host: python3 host registered plugins ['ultest']
remote/host: generated rplugin manifest: /Users/anand/.local/share/nvim/rplugin.vim
remote/host: python3 host registered plugins ['semshi', 'ultest']
remote/host: generated rplugin manifest: /Users/anand/.local/share/nvim/rplugin.vim
All parsers are up-to-date!
E5108: Error executing lua Vim(call):E117: Unknown function: SemshiBufWipeout
```

Not sure why `SemshiBufWipeout` isn't working, but it does prevent `nvim-treesitter` from doing it's thing.

**Comment by jaresty** [comment]
I got this error when I tried to browse the current directory using `-`

```
E5108: Error executing lua ...m/site/pack/packer/start/lir.nvim/lua/lir/float/init.lua:107: attempt to index field 'float' (a nil value)

```

**Comment by jaresty** [comment]
For some reason `LspInstall ruby` alone doesn't seem to have gotten LSP to work for me.   LspInfo shows:

```
  0 client(s) attached to this buffer:
  0 active client(s):

  Clients that match the filetype ruby:
```

**Comment by jaresty** [comment]
For some reason it doesn't seem to run tests for me either... nothing shows up in messages but it doesn't run tests when I use ` tf`

**Comment by benmoss** [comment]
I keep getting into some mode/state where when I try to enter insert mode (via `i`, `a`, etc) I get `E523: Not allowed here`. I don't know what's triggering it but it happens pretty often when editing Go files. Any advice how to debug? I end up having to restart vim :/

**Comment by luan** [comment]
> I keep getting into some mode/state where when I try to enter insert mode (via `i`, `a`, etc) I get `E523: Not allowed here`. I don't know what's triggering it but it happens pretty often when editing Go files. Any advice how to debug? I end up having to restart vim :/

I think this may have been due to the completion plugin, can you try now with the new one?

**Comment by XenoPhex** [comment]
Started getting this after the latest update whenever I'd use FZF/`Ctrl+p`:
```
Error detected while processing function fzf#vim#files[15]..<SNR>224_fzf[21]..fzf#run[63]..<SNR>60_execute_term[93]..<SNR>60_dopopd:
line   20:
E716: Key not present in Dictionary: "dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))"
E15: Invalid expression: s:fzf_getcwd() ==# w:fzf_pushd.dir && (!&autochdir || w:fzf_pushd.bufname ==# bufname(''))
```

**Comment by kirederik** [comment]
Pulled the latest changes, started to get some errors at startup

```packer.nvim: Error running config for nvim-compe: [string "..."]:0: module 'plugins.compe' not found:
^Ino field package.preload['plugins.compe']
^Ino file './plugins/compe.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/plugins/compe.lua'
^Ino file '/usr/local/share/lua/5.1/plugins/compe.lua'
^Ino file '/usr/local/share/lua/5.1/plugins/compe/init.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/plugins/compe.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/plugins/compe/init.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/plugins/compe.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/plugins/compe/init.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/plugins/compe.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/plugins/compe/init.lua'
^Ino file './plugins/compe.so'
^Ino file '/usr/local/lib/lua/5.1/plugins/compe.so'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/plugins/compe.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/plugins/compe.so'
^Ino file './plugins.so'
^Ino file '/usr/local/lib/lua/5.1/plugins.so'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/plugins.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/plugins.so'
Press ENTER or type command to continue
packer.nvim: Error running config for auto-session: [string "..."]:0: module 'auto-session' not found:
^Ino field package.preload['auto-session']
^Ino file './auto-session.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/luajit-2.1.0-beta3/auto-session.lua'
^Ino file '/usr/local/share/lua/5.1/auto-session.lua'
^Ino file '/usr/local/share/lua/5.1/auto-session/init.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/auto-session.lua'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/share/lua/5.1/auto-session/init.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/auto-session.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/auto-session/init.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/auto-session.lua'
^Ino file '/Users/ederik/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/auto-session/init.lua'
^Ino file './auto-session.so'
^Ino file '/usr/local/lib/lua/5.1/auto-session.so'
^Ino file '/usr/local/Cellar/luajit-openresty/2.1-20210510/lib/lua/5.1/auto-session.so'
^Ino file '/usr/local/lib/lua/5.1/loadall.so'
Press ENTER or type command to continue```

**Comment by jaresty** [comment]
Are you open to switching the test runner back to the tmux test runner?  That was working better for me.

**Comment by benmoss** [comment]
Some of the `g` shortcuts in https://github.com/luan/nvim/pull/55/files#diff-8c1ed0d247790076998896e30817a1b777a758bdcb2ca459440dd8f502f4a2afR76-R85 are colliding with the ones that come with which-key.nvim: https://github.com/folke/which-key.nvim/blob/b582c9d78f0d105041ed29ec3a8ee11d98ddfd50/lua/which-key/plugins/presets/misc.lua#L72-L80

`gi` for instance is the one I really am missing. Any desire to remap these? Or just get rid of the which-key defaults? I tried to but couldn't figure out how to set it which-key configuration.

My `g` completion:
Screen Shot 2021-09-29 at 3 09 52 PM

**Comment by luan** [comment]
> Some of the `g` shortcuts in https://github.com/luan/nvim/pull/55/files#diff-8c1ed0d247790076998896e30817a1b777a758bdcb2ca459440dd8f502f4a2afR76-R85 are colliding with the ones that come with which-key.nvim: https://github.com/folke/which-key.nvim/blob/b582c9d78f0d105041ed29ec3a8ee11d98ddfd50/lua/which-key/plugins/presets/misc.lua#L72-L80
> 
> `gi` for instance is the one I really am missing. Any desire to remap these? Or just get rid of the which-key defaults? I tried to but couldn't figure out how to set it which-key configuration.
> 
> My `g` completion: Screen Shot 2021-09-29 at 3 09 52 PM

Oh man, that's annoying; I didn't realize I was overriding defaults with that one (which-key just re-maps defaults for documentation purposes). I'll switch "go to i**m**plementation" to `gm`

**Comment by benmoss** [comment]
Whenever I do a `:ConfigUpdate` when there are remote changes I get this error:
```
#[packer.nvim] [ERROR 10:05:30] async.lua:20: Error in coroutine: /home/cesium/.config/nvim/lua/plugins.lua:5: E5560: nvim_exec must not be called in a lua loop callback
```

I found a similar issue [in packer itself](https://github.com/wbthomason/packer.nvim/issues/375), but not clear how to fix it here.

**Comment by luan** [comment]
> Whenever I do a `:ConfigUpdate` when there are remote changes I get this error:
> 
> ```
> #[packer.nvim] [ERROR 10:05:30] async.lua:20: Error in coroutine: /home/cesium/.config/nvim/lua/plugins.lua:5: E5560: nvim_exec must not be called in a lua loop callback
> ```
> 
> I found a similar issue [in packer itself](https://github.com/wbthomason/packer.nvim/issues/375), but not clear how to fix it here.

I think it should be fixed now in https://github.com/luan/nvim/pull/55/commits/5eb47f03ccc4d50270a2c00f3f97c9051d61f35d (but you'll get the error one more time when you pull that one down)

**Comment by luan** [comment]
Because running config update in `master` would explode. I need to take
some time and make that not suck, or maybe I just let it explode :P

On October 16, 2021, GitHub ***@***.***> wrote:
> At this point why don't you just merge this. It works fine imo.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/luan/nvim/pull/55#issuecomment-944963040>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AABWUEEK35DMSEIR5DIW2FDUHGZVBANCNFSM5ARPANEQ>.

**Pull request merged**
